//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionitem
    {
        public int ActionItemID { get; set; }
        public string ParentType { get; set; }
        public int ParentItemID { get; set; }
        public int childItemID { get; set; }
    }
}
