//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class announcement
    {
        public int announcementID { get; set; }
        public int ministryID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Message { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string Title { get; set; }

        public string AnnouncementDate { get { return string.Format("Date: {0} - {1}",BeginDate,EndDate); } }
        public virtual ministry ministry {set; get;}
         public IEnumerable<HttpPostedFileBase> files { get; set; }
	
    }
}
