//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int attendanceID { get; set; }
        public int memberID { get; set; }
        public System.DateTime RollCall { get; set; }
        public int calendarID { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual member member { get; set; }
        public virtual calendar calendar { get; set; }
    }
}
