//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankaccount
    {
        public int bankAccountID { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string Description { get; set; }
        public string ControlName { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }
        public bool IsBudgeted { get; set; }

        public string BankNameAccountNumber { get { return BankName + " (" + AccountNumber + ")"; } }

        public virtual ICollection<bankbalance> BankTransactionBalance { get; set; }
        public virtual ICollection<expense> Expenses { get; set; }
        public virtual ICollection<income> Incomes { get; set; }
        public virtual ICollection<payee> Payees { get; set; }
        public virtual ICollection<subcategory> SubCategories { get; set; }

        public virtual DateTime BeginDate { get; set; }
        public virtual decimal BeginningBalance { get; set; }
        public virtual decimal CurrentRevenueTotalAmount { get; set; }
        public virtual decimal CurrentExpenseTotalAmount { get; set; }
        public virtual decimal EndingBalance { get { return (BeginningBalance + CurrentRevenueTotalAmount - CurrentExpenseTotalAmount); } }

    }
}
