//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankbalance
    {
        public int BankBalanceID { get; set; }
        public int BankAccountID { get; set; }
        public int LastIncomeID { get; set; }
        public int LastExpenseID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal BeginingBalance { get; set; }
        public decimal RevenueAmount { get; set; }
        public decimal ExpenseAmount { get; set; }
        public decimal EndingBalance { get; set; }

        public virtual bankaccount bankaccount { get; set; }

    }
}
