//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int billID { get; set; }
        public int payeeID { get; set; }
        public string PayeeName { get; set; }
        public string AccountNumber { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal AmountDue { get; set; }
        public System.DateTime DateDue { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual payee payee { get; set; }

        public virtual payee Returnpayee { get; set; }
        public DateTime ReturnBeginDate { get; set; }
        public DateTime ReturnEndDate { get; set; }
        public int ReturnBillID { get; set; }
        public string ReturnType { get; set; }
    }
}
