//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget
    {
        public int budgetID { get; set; }
        public short BudgetYear { get; set; }
        public string Type { get; set; }
        public int SubCategoryID { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual subcategory subcategory { get; set; }
        public decimal Ratio { get; set; }
        public decimal TotalActualAmount { get; set; }
    }
}
