//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class contribution
    {
        public int contributionID { get; set; }
        public int memberID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ContributionDate { get; set; }
        public string CheckNumber { get; set; }
        public int subCategoryID { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual member member { get; set; }
        public string FundName { get; set; }

        public DateTime ReturnBeginDate { get; set; }
        public DateTime ReturnEndDate { get; set; }
        public string ReturnType { get; set; }
        public string ReturnSearchType { get; set; }
        public int ReturnCodeID { get; set; }

        public decimal Amount2 { get; set; }
        public int subCategoryID2 { get; set; }

        public decimal Amount3 { get; set; }
        public int subCategoryID3 { get; set; }

        public decimal Amount4 { get; set; }
        public int subCategoryID4 { get; set; }

        public decimal Amount5 { get; set; }
        public int subCategoryID5 { get; set; }

        public decimal Amount6 { get; set; }
        public int subCategoryID6 { get; set; }

    }
}
