//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class document
    {
        public int documentID { get; set; }
        public Nullable<int> ministryID { get; set; }
        public string Title { get; set; }
        public int DocumentTypeID { get; set; }
        public string ContentType { get; set; }
        public int ContentLength { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Author { get; set; }
        public string Version { get; set; }
        public string FileName { get; set; }
        public string TempFileName { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        
         public IEnumerable<HttpPostedFileBase> files { get; set; }
    }
}
