//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int expenseID { get; set; }
        public int subCategoryID { get; set; }
        public int bankAccountID { get; set; }
        public string Payee { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public decimal Amount { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<bool> Reconcile { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual subcategory subcategory { get; set; }
        public virtual bankaccount bankaccount { get; set; }
        public int PendingBillID { get; set; }
    }
}
