//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class family
    {
        public int familyID { get; set; }
        public string FamilyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string Address2 { get; set; }

        public string FullAddress { get { return Address + " - " + Address2 + ", " + City + " " + State + " " + Zip; } }
        public virtual ICollection<member> FamilyMembers { get; set; }
    }
}
