//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class income
    {
        public string Title { get; set; }
        public int incomeID { get; set; }
        public int subCategoryID { get; set; }
        public int bankAccountID { get; set; }
        public System.DateTime IncomeDate { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<decimal> CheckAmount { get; set; }
        public Nullable<decimal> CoinAmount { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual subcategory subcategory { get; set; }
        public virtual bankaccount bankaccount { get; set; }
        public decimal TotalIncome { get; set; }
    }
}
