//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class listtable
    {
        public int listTableID { get; set; }
        public int ministryID { get; set; }
        public string Title { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<bool> DefaultOpen { get; set; }
        public Nullable<bool> IsPublic { get; set; }

        public virtual ICollection<listheader> listheaders { get; set; }
        public virtual ICollection<listitem> listitems { get; set; }

    }
}
