//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetingnote
    {
        public int meetingNoteID { get; set; }
        public int MeetingAgendaID { get; set; }
        public string Note { get; set; }
        public System.DateTime NoteDate { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual meetingagenda meetingagenda { get; set; }
    }
}
