//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetingagenda
    {
        public int meetingAgendaID { get; set; }
        public int meetingID { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public int TaskID { get; set; }
        public System.DateTime DateEntered { get; set; }

        public bool HasNotes { get; set; }
        public virtual ICollection<meetingnote> MeetingNotes { get; set; }
        public virtual task task { get; set; }
        public virtual ICollection<task> ActionItems { get; set; }
    }
}
