//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class churchdatabaseEntities : DbContext
    {
        public churchdatabaseEntities()
            : base("name=churchdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actionitem> actionitems { get; set; }
        public DbSet<announcement> announcements { get; set; }
        public DbSet<attendance> attendances { get; set; }
        public DbSet<bankaccount> bankaccounts { get; set; }
        public DbSet<bankbalance> bankbalances { get; set; }
        public DbSet<bill> bills { get; set; }
        public DbSet<budget> budgets { get; set; }
        public DbSet<budgetitem> budgetitems { get; set; }
        public DbSet<calendar> calendars { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<childparent> childparents { get; set; }
        public DbSet<constant> constants { get; set; }
        public DbSet<contribution> contributions { get; set; }
        public DbSet<document> documents { get; set; }
        public DbSet<expense> expenses { get; set; }
        public DbSet<family> families { get; set; }
        public DbSet<goal> goals { get; set; }
        public DbSet<income> incomes { get; set; }
        public DbSet<listheader> listheaders { get; set; }
        public DbSet<listitem> listitems { get; set; }
        public DbSet<listtable> listtables { get; set; }
        public DbSet<meeting> meetings { get; set; }
        public DbSet<meetingagenda> meetingagendas { get; set; }
        public DbSet<meetingnote> meetingnotes { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<ministry> ministries { get; set; }
        public DbSet<ministryexpense> ministryexpenses { get; set; }
        public DbSet<ministrygroup> ministrygroups { get; set; }
        public DbSet<ministryincome> ministryincomes { get; set; }
        public DbSet<ministrymember> ministrymembers { get; set; }
        public DbSet<payee> payees { get; set; }
        public DbSet<payeecategory> payeecategories { get; set; }
        public DbSet<picture> pictures { get; set; }
        public DbSet<pledge> pledges { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productdiscount> productdiscounts { get; set; }
        public DbSet<programevent> programevents { get; set; }
        public DbSet<programeventbudget> programeventbudgets { get; set; }
        public DbSet<programeventbudgetitem> programeventbudgetitems { get; set; }
        public DbSet<property> properties { get; set; }
        public DbSet<propertyinventory> propertyinventories { get; set; }
        public DbSet<responsibility> responsibilities { get; set; }
        public DbSet<sale> sales { get; set; }
        public DbSet<saleitem> saleitems { get; set; }
        public DbSet<spouse> spouses { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<story> stories { get; set; }
        public DbSet<subcategory> subcategories { get; set; }
        public DbSet<subcategoryitem> subcategoryitems { get; set; }
        public DbSet<supervisor> supervisors { get; set; }
        public DbSet<task> tasks { get; set; }
        public DbSet<video> videos { get; set; }
        public DbSet<visitor> visitors { get; set; }
    }
}
