//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class picture
    {
        public int pictureID { get; set; }
        public int ministryID { get; set; }
        public System.DateTime PictureDate { get; set; }
        public string Description { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
        public string PictureType { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        

        public virtual ministry ministry { get; set; }
	    public IEnumerable<HttpPostedFileBase> files { get; set; }
	    public string GroupDescription { get; set; }
    }
}
