//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class pledge
    {
        public int pledgeID { get; set; }
        public int memberID { get; set; }
        public int FundID { get; set; }
        public string Type { get; set; }
        public string FundName { get; set; }
        public decimal Amount { get; set; }
        public short PledgeYear { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual member member { get; set; }
        public virtual decimal RatioCompleted { get; set; }
        public decimal TotalAmountPaid { get; set; }

        public int ReturnPledgeYear { get; set; }
        public string ReturnSearchType { get; set; }
        public int ReturnCodeID { get; set; }
        public string ReturnCode { get; set; }
    }
}
