//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class programevent
    {
        public int programEventID { get; set; }
        public int goalID { get; set; }
        public string Title { get; set; }
        public System.DateTime C_When { get; set; }
        public int C_Who { get; set; }
        public string C_Where { get; set; }
        public string C_What { get; set; }
        public string C_How { get; set; }
        public string BeginTime { get; set; }
        public string EndTime { get; set; }
        public string Status { get; set; }
        public int CalendarID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public string EventContact { get; set; }
        public virtual goal goal { get; set; }

        public virtual ICollection<programeventbudget> ProgramEventBudgets { get; set; }
        public string DateBeginEndTime { get { return string.Format("{0} {1} - {2}", C_When.ToString("D"), BeginTime, EndTime); } }

        public member member { get; set; }
        public calendar calendar { get; set; }
        public document document { get; set; }

    }
}
