//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsibility
    {
        public int responsibilityID { get; set; }
        public int staffID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
        public string FullDescription { get; set; }
        public string BriefDescription { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual staff staff { get; set; }
    }
}
