//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int saleID { get; set; }
        public System.DateTime saleDate { get; set; }
        public decimal saleAmount { get; set; }
        public int NumberProduct { get; set; }
        public string Cashier { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
        public string CheckNumber { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual ICollection<saleitem> SaleItems { get; set; }
    }
}
