//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> pictureID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

         
 	    public virtual ICollection<responsibility> Responsibilities { get; set; }
 	    public IEnumerable<HttpPostedFileBase> files { get; set; }
        public virtual picture picture { get; set;}
        public virtual responsibility mainResponsibility { get; set; }
	    public string FullNameTitle { get { return Title + " " + FirstName + " " + MiddleName + " " + LastName; } }

    }
}
