//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategory
    {
        public int subCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public int categoryID { get; set; }
        public int bankAccountID { get; set; }
        public string ShortTitle { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public category category { get; set; }
        public bankaccount bankaccount { get; set; }

        public virtual string ParentCategoryName { get; set; }
        public virtual ICollection<budget> Budgets { get; set; }
        public virtual ICollection<expense> Expenses { get; set; }
        public virtual ICollection<income> Incomes { get; set; }
        public virtual ICollection<ministryexpense> MinistryExpenses { get; set; }
        public virtual ICollection<ministryincome> MinistryIncome { get; set; }
        public virtual ICollection<payee> Payees { get; set; }
        public virtual ICollection<property> Properties { get; set; }
        public virtual ICollection<visitor> Visitors { get; set; }

        public virtual string DisplayName { get; set; }
        public decimal TotalYTDAmount { get; set; }
        public int BudgetYear { get; set; }
        public string CategoryType { get; set; }
    }
}
