//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int taskID { get; set; }
        public int goalID { get; set; }
        public string Title { get; set; }
        public int AssignTo { get; set; }
        public System.DateTime AssignDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<decimal> CompletionRatio { get; set; }
        public string SupervisorComment { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual goal goal { get; set; }
        public virtual ministrymember ministrymember { get; set; }
        public virtual member member { get; set; }
        public int parentTaskID { get; set; }
        public string ActionItemTypeCode { get; set; }
    }
}
