//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userID { get; set; }
        public string Email { get; set; }
        public bool IsRegister { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string PasswordAnswer { get; set; }
        public string PasswordQuestion { get; set; }
        public int PersonID { get; set; }
        public int RoleID { get; set; }
        public int role_RoleID { get; set; }
        public string EmailType { get; set; }
        public string UserName { get; set; }

        public virtual role role { get; set; }
    }
}
