//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public int videoID { get; set; }
        public int ministryID { get; set; }
        public string VideoTitle { get; set; }
        public System.DateTime VideoDate { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<int> VideoTypeID { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public virtual ministry ministry { get; set; }
    }
}
