//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor
    {
        public int visitorID { get; set; }
        public Nullable<int> Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public int subCategoryID { get; set; }
        public Nullable<int> LastEventAttended { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<int> PhoneProviderID { get; set; }
        public string Email { get; set; }
        public Nullable<int> BestContact { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }

        public string VisitorCategory { get; set; }
        public virtual subcategory subcategory { get; set; }
        public string Title2 { get; set; }
        public string BestContactType { get; set; }
        public string LastEventName { get; set; }

        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
    }
}
